// XD-4 factory programs.

import { createProgramBank, type FactoryProgram } from '../core/programs'
import { PARAMS, type Patch } from './params'

const FACTORY: FactoryProgram<Patch>[] = [
  { name: 'Init Program', patch: {} },
  {
    name: 'Analog Brass',
    patch: {
      vco2Pitch: 0.08,
      vco2Level: 0.8,
      cutoff: 0.45,
      resonance: 0.15,
      keyTrack: '50',
      egAttack: 0.25,
      egDecay: 0.45,
      egInt: 0.55,
      ampAttack: 0.2,
      ampDecay: 0.5,
      ampSustain: 0.8,
      ampRelease: 0.3,
      reverbOn: 'on',
      reverbDepth: 0.3,
    },
  },
  {
    name: 'Silk Pad',
    patch: {
      vco1Shape: 0.3,
      vco2Pitch: 0.12,
      vco2Shape: 0.3,
      vco2Level: 0.85,
      cutoff: 0.55,
      ampAttack: 0.62,
      ampDecay: 0.6,
      ampSustain: 0.85,
      ampRelease: 0.62,
      lfoRate: 0.3,
      lfoInt: 0.4,
      lfoTarget: 'shape',
      modFxOn: 'on',
      modFxType: 'chorus',
      reverbOn: 'on',
      reverbTime: 0.7,
      reverbDepth: 0.6,
    },
  },
  {
    name: 'Unison Bass',
    patch: {
      voiceMode: 'unison',
      voiceDepth: 0.35,
      portamento: 0.15,
      vco1Octave: '16',
      vco2Wave: 'sqr',
      vco2Octave: '16',
      vco2Shape: 0.2,
      vco2Level: 0.7,
      cutoff: 0.38,
      resonance: 0.35,
      drive: '50',
      egDecay: 0.35,
      egInt: 0.5,
      ampDecay: 0.45,
      ampSustain: 0.7,
      ampRelease: 0.1,
    },
  },
  {
    name: 'Glass Pluck',
    patch: {
      vco1Wave: 'tri',
      vco1Shape: 0.4,
      vco2Wave: 'tri',
      vco2Octave: '4',
      vco2Level: 0.5,
      cutoff: 0.35,
      resonance: 0.4,
      keyTrack: '100',
      egDecay: 0.35,
      egInt: 0.65,
      ampDecay: 0.45,
      ampSustain: 0,
      ampRelease: 0.4,
      delayOn: 'on',
      delayType: 'pingpong',
      delayTime: 0.45,
      delayDepth: 0.4,
      reverbOn: 'on',
      reverbDepth: 0.3,
    },
  },
  {
    name: 'Ring Bell',
    patch: {
      vco1Wave: 'tri',
      vco2Wave: 'sqr',
      vco2Octave: '4',
      vco2Pitch: 0.35,
      ring: 'on',
      vco1Level: 0,
      vco2Level: 1,
      cutoff: 0.85,
      ampDecay: 0.6,
      ampSustain: 0,
      ampRelease: 0.6,
      reverbOn: 'on',
      reverbType: 'plate',
      reverbTime: 0.6,
      reverbDepth: 0.5,
    },
  },
  {
    name: 'VPM Keys',
    patch: {
      multiEngine: 'vpm',
      multiVpmType: 'sin1',
      multiShape: 0.25,
      vco1Level: 0,
      multiLevel: 1,
      cutoff: 0.8,
      ampDecay: 0.62,
      ampSustain: 0.25,
      ampRelease: 0.4,
      modFxOn: 'on',
      modFxDepth: 0.4,
      reverbOn: 'on',
      reverbType: 'room',
      reverbDepth: 0.4,
    },
  },
  {
    name: 'Noise Wind',
    patch: {
      multiEngine: 'noise',
      multiNoiseType: 'peak',
      multiShape: 0.5,
      vco1Level: 0,
      multiLevel: 1,
      lfoRate: 0.25,
      lfoInt: 0.5,
      lfoTarget: 'shape',
      ampAttack: 0.6,
      ampRelease: 0.7,
      reverbOn: 'on',
      reverbTime: 0.8,
      reverbDepth: 0.6,
    },
  },
  {
    name: 'Arp Sparkle',
    patch: {
      tempo: 124,
      voiceMode: 'arp',
      voiceDepth: 0.35,
      vco1Wave: 'sqr',
      vco1Shape: 0.3,
      vco2Octave: '4',
      vco2Level: 0.4,
      cutoff: 0.5,
      resonance: 0.3,
      egDecay: 0.25,
      egInt: 0.4,
      ampDecay: 0.35,
      ampSustain: 0,
      delayOn: 'on',
      delayType: 'pingpong',
      delayTime: 0.4,
      delayDepth: 0.45,
    },
  },
  {
    name: 'Minor 7 Stab',
    patch: {
      voiceMode: 'chord',
      voiceDepth: 0.4,
      vco2Pitch: 0.1,
      vco2Level: 0.7,
      cutoff: 0.5,
      egDecay: 0.3,
      egInt: 0.5,
      ampDecay: 0.4,
      ampSustain: 0,
      ampRelease: 0.25,
      reverbOn: 'on',
      reverbType: 'plate',
      reverbDepth: 0.35,
    },
  },
  {
    name: 'Wobble Bass',
    patch: {
      tempo: 140,
      voiceMode: 'unison',
      voiceDepth: 0.2,
      vco1Octave: '16',
      vco2Wave: 'sqr',
      vco2Octave: '16',
      vco2Level: 0.8,
      cutoff: 0.3,
      resonance: 0.5,
      drive: '50',
      lfoWave: 'tri',
      lfoMode: 'bpm',
      lfoRate: 0.58,
      lfoInt: 0.6,
      lfoTarget: 'cutoff',
    },
  },
  {
    name: 'X-Mod Lead',
    patch: {
      voiceMode: 'unison',
      voiceDepth: 0.15,
      portamento: 0.25,
      vco1Level: 0.4,
      vco2Pitch: 0.4,
      vco2Level: 0.8,
      crossMod: 0.35,
      cutoff: 0.6,
      resonance: 0.2,
      lfoRate: 0.55,
      lfoInt: 0.12,
      lfoTarget: 'pitch',
      delayOn: 'on',
      delayDepth: 0.3,
    },
  },
  {
    name: 'Seq Bassline',
    patch: {
      tempo: 118,
      vco2Wave: 'sqr',
      vco2Octave: '16',
      vco2Level: 0.5,
      cutoff: 0.3,
      resonance: 0.55,
      egDecay: 0.3,
      egInt: 0.6,
      ampDecay: 0.35,
      ampSustain: 0.3,
      ampRelease: 0.1,
      delayOn: 'on',
      delayTime: 0.35,
      delayDepth: 0.2,
    },
    sequence: [36, null, 36, 48, null, 36, 39, null, 36, null, 43, 36, null, 46, 48, 36],
  },
]

export const programs = createProgramBank({
  params: PARAMS,
  factory: FACTORY,
  // Kept from the single-synth version so programs written before still load.
  storageKey: 'xd4-web.programs.v1',
  count: 100,
})
