// Model D factory programs. The hardware has no memory; these are the kind of
// patch sheets players wrote down, stored here so they can be recalled.

import { createProgramBank, type FactoryProgram } from '../core/programs'
import { PARAMS, type Patch } from './params'

const FACTORY: FactoryProgram<Patch>[] = [
  { name: 'Basic Saw', patch: {} },
  {
    name: 'Classic Bass',
    patch: {
      osc1Range: '16',
      osc2Range: '16',
      osc2Freq: 0.012,
      osc2On: 'on',
      osc3Range: '32',
      osc3Wave: 'square',
      osc3Freq: -0.01,
      osc3On: 'on',
      osc3Level: 0.6,
      cutoff: 0.32,
      emphasis: 0.35,
      contourAmount: 0.55,
      filterDecay: 0.35,
      filterSustain: 0.15,
      loudDecay: 0.4,
      loudSustain: 0.8,
      keyTrack1: 'on',
    },
  },
  {
    name: 'Lead Glide',
    patch: {
      glideOn: 'on',
      glide: 0.3,
      osc2Wave: 'square',
      osc2Freq: 0.015,
      osc2On: 'on',
      osc3Range: '4',
      osc3Wave: 'saw',
      osc3On: 'on',
      osc3Level: 0.5,
      cutoff: 0.5,
      emphasis: 0.5,
      contourAmount: 0.5,
      filterDecay: 0.45,
      filterSustain: 0.5,
      keyTrack2: 'on',
      decaySwitch: 'on',
      loudDecay: 0.35,
      modSourceB: 'lfo',
      modMix: 1,
      modDepth: 0,
      lfoRate: 0.42,
      oscMod: 'on',
    },
  },
  {
    name: 'Brass',
    patch: {
      osc2Freq: 0.02,
      osc2On: 'on',
      osc3Freq: -0.02,
      osc3Wave: 'saw',
      osc3On: 'on',
      cutoff: 0.35,
      emphasis: 0.15,
      contourAmount: 0.6,
      filterAttack: 0.35,
      filterDecay: 0.45,
      filterSustain: 0.55,
      loudAttack: 0.15,
      loudSustain: 0.9,
      decaySwitch: 'on',
      loudDecay: 0.4,
    },
  },
  {
    name: 'Fifths',
    patch: {
      osc2Freq: 1,
      osc2On: 'on',
      osc2Wave: 'trisaw',
      osc1Wave: 'trisaw',
      cutoff: 0.45,
      emphasis: 0.3,
      contourAmount: 0.45,
      filterDecay: 0.4,
      filterSustain: 0.3,
      keyTrack1: 'on',
    },
  },
  {
    name: 'Ext Feedback',
    patch: {
      osc1Range: '16',
      extOn: 'on',
      extLevel: 0.7,
      // Feedback saturates into a dense, loud tone; trim it to sit with the others.
      volume: 0.45,
      cutoff: 0.4,
      emphasis: 0.45,
      contourAmount: 0.4,
      filterDecay: 0.4,
      filterSustain: 0.4,
    },
  },
  {
    name: 'Osc3 Wobble',
    patch: {
      osc1Range: '16',
      osc2Range: '16',
      osc2Freq: 0.01,
      osc2On: 'on',
      osc3Range: 'lo',
      osc3Wave: 'tri',
      osc3Control: 'off',
      osc3Freq: 0.6,
      cutoff: 0.3,
      emphasis: 0.55,
      contourAmount: 0.2,
      filterSustain: 0.6,
      filterMod: 'on',
      modSourceA: 'osc3',
      modMix: 0,
      modDepth: 0.7,
    },
  },
  {
    name: 'Flute',
    patch: {
      osc1Wave: 'tri',
      osc1Range: '4',
      noiseOn: 'on',
      noiseLevel: 0.12,
      noiseColor: 'pink',
      cutoff: 0.55,
      contourAmount: 0.15,
      filterAttack: 0.25,
      filterSustain: 0.7,
      loudAttack: 0.22,
      loudSustain: 0.85,
      decaySwitch: 'on',
      loudDecay: 0.3,
      modSourceB: 'lfo',
      modMix: 1,
      modDepth: 0,
      lfoRate: 0.45,
      oscMod: 'on',
    },
  },
  {
    name: 'Noise Snare',
    patch: {
      osc1On: 'off',
      noiseOn: 'on',
      noiseLevel: 1,
      osc3On: 'on',
      osc3Range: '16',
      osc3Wave: 'tri',
      osc3Level: 0.5,
      cutoff: 0.55,
      contourAmount: 0.3,
      filterDecay: 0.25,
      filterSustain: 0,
      loudDecay: 0.27,
      loudSustain: 0,
      decaySwitch: 'on',
      volume: 1,
    },
  },
  {
    name: 'Arp Pulse',
    patch: {
      arp: 'on',
      arpMode: 'risefall',
      arpRange: '2',
      arpRate: '16n',
      arpGate: 0.4,
      tempo: 124,
      osc1Wave: 'wide',
      osc2Wave: 'saw',
      osc2Range: '4',
      osc2Freq: 0.01,
      osc2On: 'on',
      osc2Level: 0.5,
      cutoff: 0.4,
      emphasis: 0.45,
      contourAmount: 0.5,
      filterDecay: 0.28,
      filterSustain: 0.1,
      keyTrack1: 'on',
      loudDecay: 0.3,
      loudSustain: 0.6,
    },
  },
]

export const programs = createProgramBank({
  params: PARAMS,
  factory: FACTORY,
  storageKey: 'model-d-web.programs.v1',
  count: 50,
})
